### PR TITLE
remove `_grunt-xml-sitemap.sublime-project` file

### PR DESCRIPTION
**Pull request by ArmorDarks**
It's very opinionated file, tied to working environment. It shouldn't be in repository.

### CODE REVIEW

**Comment by furzeface** [comment]
Going to keep it in, in case I work on this project. 

Unless [you want to help out](https://github.com/furzeface/grunt-xml-sitemap/issues/11)?

Would be worth adding an `.npmignore` anyway for that file and a few others so they don't get published to the actual NPM module, so thanks for highlighting that for me!

**Comment by ArmorDarks** [comment]
Sure, as you wish.

> Unless you want to help out?

@MrHyde came out with written from scratch version https://github.com/LotusTM/grunt-sitemap-xml, so we're going to continue work there

**Comment by furzeface** [comment]
I'll work on changing NPM publish rights too then ASAP. 

Also is it worth me transferring repo ownership, or making collaborators?

**Comment by mrhyde** [comment]
Collaborators should be enough :)

**Pull request closed without merging**
